-- MySQL Script generated by MySQL Workbench
-- Thu May  8 19:41:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sampleschema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sampleschema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sampleschema` DEFAULT CHARACTER SET utf8mb3 ;
USE `sampleschema` ;

-- -----------------------------------------------------
-- Table `sampleschema`.`oc_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `firstname` VARCHAR(32) NULL DEFAULT NULL,
  `lastname` VARCHAR(32) NULL DEFAULT NULL,
  `company` VARCHAR(60) NULL DEFAULT NULL,
  `address_1` VARCHAR(128) NULL DEFAULT NULL,
  `address_2` VARCHAR(128) NULL DEFAULT NULL,
  `city` VARCHAR(128) NULL DEFAULT NULL,
  `postcode` VARCHAR(10) NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT '0',
  `zone_id` INT NULL DEFAULT '0',
  `custom_field` TEXT NULL DEFAULT NULL,
  `default` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_address_format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_address_format` (
  `address_format_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `address_format` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`address_format_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_antispam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_antispam` (
  `antispam_id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`antispam_id`),
  INDEX `keyword` (`keyword` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_api` (
  `api_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NULL DEFAULT NULL,
  `key` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`api_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_api_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_api_history` (
  `api_history_id` INT NOT NULL AUTO_INCREMENT,
  `api_id` INT NULL DEFAULT NULL,
  `call` VARCHAR(32) NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`api_history_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_api_ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_api_ip` (
  `api_ip_id` INT NOT NULL AUTO_INCREMENT,
  `api_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`api_ip_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NULL DEFAULT NULL,
  `author` VARCHAR(64) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article_comment` (
  `article_comment_id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NULL DEFAULT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `author` VARCHAR(64) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT '0',
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`article_comment_id`),
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `parent_id` (`parent_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article_description` (
  `article_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `tag` TEXT NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`, `language_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article_rating` (
  `article_rating_id` INT NOT NULL AUTO_INCREMENT,
  `article_comment_id` INT NULL DEFAULT NULL,
  `article_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT '0',
  `customer_id` INT NULL DEFAULT NULL,
  `rating` TINYINT(1) NULL DEFAULT '0',
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`article_rating_id`),
  INDEX `article_comment_id` (`article_comment_id` ASC) VISIBLE,
  INDEX `article_id` (`article_id` ASC) VISIBLE,
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article_to_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article_to_layout` (
  `article_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `layout_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_article_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_article_to_store` (
  `article_id` INT NOT NULL,
  `store_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`article_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_attribute` (
  `attribute_id` INT NOT NULL AUTO_INCREMENT,
  `attribute_group_id` INT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_attribute_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_attribute_description` (
  `attribute_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_attribute_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_attribute_group` (
  `attribute_group_id` INT NOT NULL AUTO_INCREMENT,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_group_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_attribute_group_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_attribute_group_description` (
  `attribute_group_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_group_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_banner` (
  `banner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`banner_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_banner_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_banner_image` (
  `banner_image_id` INT NOT NULL AUTO_INCREMENT,
  `banner_id` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT '0',
  PRIMARY KEY (`banner_image_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 181
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT '0',
  `customer_id` INT NULL DEFAULT '0',
  `session_id` VARCHAR(32) NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `subscription_plan_id` INT NULL DEFAULT '0',
  `option` TEXT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `override` TINYINT(1) NULL DEFAULT NULL,
  `price` DECIMAL(15,4) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `cart_id` (`customer_id` ASC, `session_id` ASC, `product_id` ASC, `subscription_plan_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `parent_id` INT NULL DEFAULT '0',
  `column` INT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `parent_id` (`parent_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category_description` (
  `category_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`, `language_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category_filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category_filter` (
  `category_id` INT NOT NULL,
  `filter_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `filter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category_path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category_path` (
  `category_id` INT NOT NULL,
  `path_id` INT NOT NULL,
  `level` INT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`, `path_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category_to_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category_to_layout` (
  `category_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `layout_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_category_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_category_to_store` (
  `category_id` INT NOT NULL,
  `store_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`category_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `iso_code_2` VARCHAR(2) NULL DEFAULT NULL,
  `iso_code_3` VARCHAR(3) NULL DEFAULT NULL,
  `address_format_id` INT NULL DEFAULT NULL,
  `postcode_required` TINYINT(1) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 258
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_coupon` (
  `coupon_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `code` VARCHAR(20) NULL DEFAULT NULL,
  `type` CHAR(1) NULL DEFAULT NULL,
  `discount` DECIMAL(15,4) NULL DEFAULT NULL,
  `logged` TINYINT(1) NULL DEFAULT NULL,
  `shipping` TINYINT(1) NULL DEFAULT NULL,
  `total` DECIMAL(15,4) NULL DEFAULT NULL,
  `date_start` DATE NULL DEFAULT NULL,
  `date_end` DATE NULL DEFAULT NULL,
  `uses_total` INT NULL DEFAULT NULL,
  `uses_customer` INT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`coupon_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_coupon_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_coupon_category` (
  `coupon_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`coupon_id`, `category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_coupon_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_coupon_history` (
  `coupon_history_id` INT NOT NULL AUTO_INCREMENT,
  `coupon_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `amount` DECIMAL(15,4) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`coupon_history_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_coupon_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_coupon_product` (
  `coupon_product_id` INT NOT NULL AUTO_INCREMENT,
  `coupon_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`coupon_product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_cron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_cron` (
  `cron_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(128) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cycle` VARCHAR(12) NULL DEFAULT NULL,
  `action` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cron_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_currency` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(32) NULL DEFAULT NULL,
  `code` VARCHAR(3) NULL DEFAULT NULL,
  `symbol_left` VARCHAR(12) NULL DEFAULT NULL,
  `symbol_right` VARCHAR(12) NULL DEFAULT NULL,
  `decimal_place` INT NULL DEFAULT NULL,
  `value` DOUBLE(15,8) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_custom_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_custom_field` (
  `custom_field_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `validation` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(10) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`custom_field_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_custom_field_customer_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_custom_field_customer_group` (
  `custom_field_id` INT NOT NULL,
  `customer_group_id` INT NOT NULL,
  `required` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`custom_field_id`, `customer_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_custom_field_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_custom_field_description` (
  `custom_field_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`custom_field_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_custom_field_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_custom_field_value` (
  `custom_field_value_id` INT NOT NULL AUTO_INCREMENT,
  `custom_field_id` INT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`custom_field_value_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_custom_field_value_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_custom_field_value_description` (
  `custom_field_value_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `custom_field_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`custom_field_value_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_group_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT '0',
  `language_id` INT NULL DEFAULT NULL,
  `firstname` VARCHAR(32) NULL DEFAULT NULL,
  `lastname` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `telephone` VARCHAR(32) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `custom_field` TEXT NULL DEFAULT NULL,
  `newsletter` TINYINT(1) NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `safe` TINYINT(1) NULL DEFAULT NULL,
  `commenter` TINYINT(1) NULL DEFAULT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(40) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_activity` (
  `customer_activity_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `key` VARCHAR(64) NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_activity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_affiliate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_affiliate` (
  `customer_id` INT NOT NULL,
  `company` VARCHAR(60) NULL DEFAULT NULL,
  `website` VARCHAR(255) NULL DEFAULT NULL,
  `tracking` VARCHAR(64) NULL DEFAULT NULL,
  `balance` DECIMAL(15,4) NULL DEFAULT NULL,
  `commission` DECIMAL(4,2) NULL DEFAULT '0.00',
  `tax` VARCHAR(64) NULL DEFAULT NULL,
  `payment_method` VARCHAR(6) NULL DEFAULT NULL,
  `cheque` VARCHAR(100) NULL DEFAULT NULL,
  `paypal` VARCHAR(64) NULL DEFAULT NULL,
  `bank_name` VARCHAR(64) NULL DEFAULT NULL,
  `bank_branch_number` VARCHAR(64) NULL DEFAULT NULL,
  `bank_swift_code` VARCHAR(64) NULL DEFAULT NULL,
  `bank_account_name` VARCHAR(64) NULL DEFAULT NULL,
  `bank_account_number` VARCHAR(64) NULL DEFAULT NULL,
  `custom_field` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_affiliate_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_affiliate_report` (
  `customer_affiliate_report_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_affiliate_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_approval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_approval` (
  `customer_approval_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `type` VARCHAR(9) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_approval_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_authorize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_authorize` (
  `customer_authorize_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `token` VARCHAR(96) NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_authorize_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_group` (
  `customer_group_id` INT NOT NULL AUTO_INCREMENT,
  `approval` INT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`customer_group_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_group_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_group_description` (
  `customer_group_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`customer_group_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_history` (
  `customer_history_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_history_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_ip` (
  `customer_ip_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_ip_id`),
  INDEX `ip` (`ip` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_login` (
  `customer_login_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_login_id`),
  INDEX `email` (`email` ASC) VISIBLE,
  INDEX `ip` (`ip` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_online` (
  `ip` VARCHAR(40) NOT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `referer` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_reward` (
  `customer_reward_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT '0',
  `order_id` INT NULL DEFAULT '0',
  `description` TEXT NULL DEFAULT NULL,
  `points` INT NULL DEFAULT '0',
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_reward_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_search` (
  `customer_search_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `keyword` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `sub_category` TINYINT(1) NULL DEFAULT NULL,
  `description` TINYINT(1) NULL DEFAULT NULL,
  `products` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_search_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_transaction` (
  `customer_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `amount` DECIMAL(15,4) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_customer_wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_customer_wishlist` (
  `customer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`, `store_id`, `product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_download` (
  `download_id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(160) NULL DEFAULT NULL,
  `mask` VARCHAR(128) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`download_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_download_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_download_description` (
  `download_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`download_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_download_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_download_report` (
  `download_report_id` INT NOT NULL AUTO_INCREMENT,
  `download_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`download_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(128) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `trigger` TEXT NULL DEFAULT NULL,
  `action` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `sort_order` INT NULL DEFAULT '1',
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_extension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_extension` (
  `extension_id` INT NOT NULL AUTO_INCREMENT,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(32) NULL DEFAULT NULL,
  `code` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`extension_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_extension_install`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_extension_install` (
  `extension_install_id` INT NOT NULL AUTO_INCREMENT,
  `extension_id` INT NULL DEFAULT NULL,
  `extension_download_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `version` VARCHAR(255) NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`extension_install_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_extension_path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_extension_path` (
  `extension_path_id` INT NOT NULL AUTO_INCREMENT,
  `extension_install_id` INT NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`extension_path_id`),
  INDEX `path` (`path` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2926
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_filter` (
  `filter_id` INT NOT NULL AUTO_INCREMENT,
  `filter_group_id` INT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`filter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_filter_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_filter_description` (
  `filter_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`filter_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_filter_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_filter_group` (
  `filter_group_id` INT NOT NULL AUTO_INCREMENT,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`filter_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_filter_group_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_filter_group_description` (
  `filter_group_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`filter_group_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_gdpr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_gdpr` (
  `gdpr_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `code` VARCHAR(40) NULL DEFAULT NULL,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `action` VARCHAR(6) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`gdpr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_geo_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_geo_zone` (
  `geo_zone_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`geo_zone_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_information` (
  `information_id` INT NOT NULL AUTO_INCREMENT,
  `sort_order` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`information_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_information_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_information_description` (
  `information_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`information_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_information_to_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_information_to_layout` (
  `information_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `layout_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`information_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_information_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_information_to_store` (
  `information_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`information_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `code` VARCHAR(5) NULL DEFAULT NULL,
  `locale` VARCHAR(255) NULL DEFAULT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`language_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_layout` (
  `layout_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`layout_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_layout_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_layout_module` (
  `layout_module_id` INT NOT NULL AUTO_INCREMENT,
  `layout_id` INT NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `position` VARCHAR(14) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`layout_module_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_layout_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_layout_route` (
  `layout_route_id` INT NOT NULL AUTO_INCREMENT,
  `layout_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `route` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`layout_route_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_length_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_length_class` (
  `length_class_id` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(15,8) NULL DEFAULT NULL,
  PRIMARY KEY (`length_class_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_length_class_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_length_class_description` (
  `length_class_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `title` VARCHAR(32) NULL DEFAULT NULL,
  `unit` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`length_class_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `telephone` VARCHAR(32) NULL DEFAULT NULL,
  `geocode` VARCHAR(32) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `open` TEXT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_manufacturer` (
  `manufacturer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_manufacturer_to_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_manufacturer_to_layout` (
  `manufacturer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `layout_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`manufacturer_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_manufacturer_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_manufacturer_to_store` (
  `manufacturer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`manufacturer_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_marketing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_marketing` (
  `marketing_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `clicks` INT NULL DEFAULT '0',
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`marketing_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_marketing_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_marketing_report` (
  `marketing_report_id` INT NOT NULL AUTO_INCREMENT,
  `marketing_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`marketing_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_modification` (
  `modification_id` INT NOT NULL AUTO_INCREMENT,
  `extension_install_id` INT NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `author` VARCHAR(64) NULL DEFAULT NULL,
  `version` VARCHAR(32) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `xml` MEDIUMTEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`modification_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_module` (
  `module_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `setting` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_notification` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`notification_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_option` (
  `option_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_option_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_option_description` (
  `option_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`option_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_option_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_option_value` (
  `option_value_id` INT NOT NULL AUTO_INCREMENT,
  `option_id` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`option_value_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_option_value_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_option_value_description` (
  `option_value_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `option_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`option_value_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NULL DEFAULT '0',
  `invoice_no` INT NULL DEFAULT '0',
  `invoice_prefix` VARCHAR(26) NULL DEFAULT NULL,
  `transaction_id` VARCHAR(100) NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT '0',
  `store_name` VARCHAR(64) NULL DEFAULT NULL,
  `store_url` VARCHAR(255) NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT '0',
  `customer_group_id` INT NULL DEFAULT '0',
  `firstname` VARCHAR(32) NULL DEFAULT NULL,
  `lastname` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `telephone` VARCHAR(32) NULL DEFAULT NULL,
  `custom_field` TEXT NULL DEFAULT NULL,
  `payment_address_id` INT NULL DEFAULT NULL,
  `payment_firstname` VARCHAR(32) NULL DEFAULT NULL,
  `payment_lastname` VARCHAR(32) NULL DEFAULT NULL,
  `payment_company` VARCHAR(60) NULL DEFAULT NULL,
  `payment_address_1` VARCHAR(128) NULL DEFAULT NULL,
  `payment_address_2` VARCHAR(128) NULL DEFAULT NULL,
  `payment_city` VARCHAR(128) NULL DEFAULT NULL,
  `payment_postcode` VARCHAR(10) NULL DEFAULT NULL,
  `payment_country` VARCHAR(128) NULL DEFAULT NULL,
  `payment_country_id` INT NULL DEFAULT NULL,
  `payment_zone` VARCHAR(128) NULL DEFAULT NULL,
  `payment_zone_id` INT NULL DEFAULT NULL,
  `payment_address_format` TEXT NULL DEFAULT NULL,
  `payment_custom_field` TEXT NULL DEFAULT NULL,
  `payment_method` TEXT NULL DEFAULT NULL,
  `shipping_address_id` INT NULL DEFAULT NULL,
  `shipping_firstname` VARCHAR(32) NULL DEFAULT NULL,
  `shipping_lastname` VARCHAR(32) NULL DEFAULT NULL,
  `shipping_company` VARCHAR(60) NULL DEFAULT NULL,
  `shipping_address_1` VARCHAR(128) NULL DEFAULT NULL,
  `shipping_address_2` VARCHAR(128) NULL DEFAULT NULL,
  `shipping_city` VARCHAR(128) NULL DEFAULT NULL,
  `shipping_postcode` VARCHAR(10) NULL DEFAULT NULL,
  `shipping_country` VARCHAR(128) NULL DEFAULT NULL,
  `shipping_country_id` INT NULL DEFAULT NULL,
  `shipping_zone` VARCHAR(128) NULL DEFAULT NULL,
  `shipping_zone_id` INT NULL DEFAULT NULL,
  `shipping_address_format` TEXT NULL DEFAULT NULL,
  `shipping_custom_field` TEXT NULL DEFAULT NULL,
  `shipping_method` TEXT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `total` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `order_status_id` INT NULL DEFAULT '0',
  `affiliate_id` INT NULL DEFAULT NULL,
  `commission` DECIMAL(15,4) NULL DEFAULT NULL,
  `marketing_id` INT NULL DEFAULT NULL,
  `tracking` VARCHAR(64) NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `language_code` VARCHAR(5) NULL DEFAULT NULL,
  `currency_id` INT NULL DEFAULT NULL,
  `currency_code` VARCHAR(3) NULL DEFAULT NULL,
  `currency_value` DECIMAL(15,8) NULL DEFAULT '1.00000000',
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `forwarded_ip` VARCHAR(40) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `accept_language` VARCHAR(255) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_history` (
  `order_history_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `order_status_id` INT NULL DEFAULT NULL,
  `notify` TINYINT(1) NULL DEFAULT '0',
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_history_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_option` (
  `order_option_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `order_product_id` INT NULL DEFAULT NULL,
  `product_option_id` INT NULL DEFAULT NULL,
  `product_option_value_id` INT NULL DEFAULT '0',
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`order_option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_product` (
  `order_product_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `master_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(64) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `total` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `tax` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `reward` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_product_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_status` (
  `order_status_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`order_status_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_subscription` (
  `order_subscription_id` INT NOT NULL AUTO_INCREMENT,
  `order_product_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `subscription_plan_id` INT NULL DEFAULT NULL,
  `trial_price` DECIMAL(10,4) NULL DEFAULT NULL,
  `trial_tax` DECIMAL(15,4) NULL DEFAULT NULL,
  `trial_frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `trial_cycle` SMALLINT NULL DEFAULT NULL,
  `trial_duration` SMALLINT NULL DEFAULT NULL,
  `trial_status` TINYINT(1) NULL DEFAULT NULL,
  `price` DECIMAL(10,4) NULL DEFAULT NULL,
  `tax` DECIMAL(15,4) NULL DEFAULT NULL,
  `frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `cycle` SMALLINT NULL DEFAULT NULL,
  `duration` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`order_subscription_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_order_total`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_order_total` (
  `order_total_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(32) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `value` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_total_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `master_id` INT NULL DEFAULT '0',
  `model` VARCHAR(64) NULL DEFAULT NULL,
  `sku` VARCHAR(64) NULL DEFAULT NULL,
  `upc` VARCHAR(12) NULL DEFAULT NULL,
  `ean` VARCHAR(14) NULL DEFAULT NULL,
  `jan` VARCHAR(13) NULL DEFAULT NULL,
  `isbn` VARCHAR(17) NULL DEFAULT NULL,
  `mpn` VARCHAR(64) NULL DEFAULT NULL,
  `location` VARCHAR(128) NULL DEFAULT NULL,
  `variant` TEXT NULL DEFAULT NULL,
  `override` TEXT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT '0',
  `stock_status_id` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `manufacturer_id` INT NULL DEFAULT NULL,
  `shipping` TINYINT(1) NULL DEFAULT '1',
  `price` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `points` INT NULL DEFAULT '0',
  `tax_class_id` INT NULL DEFAULT NULL,
  `date_available` DATE NULL DEFAULT NULL,
  `weight` DECIMAL(15,8) NULL DEFAULT '0.00000000',
  `weight_class_id` INT NULL DEFAULT '0',
  `length` DECIMAL(15,8) NULL DEFAULT '0.00000000',
  `width` DECIMAL(15,8) NULL DEFAULT '0.00000000',
  `height` DECIMAL(15,8) NULL DEFAULT '0.00000000',
  `length_class_id` INT NULL DEFAULT '0',
  `subtract` TINYINT(1) NULL DEFAULT '1',
  `minimum` INT NULL DEFAULT '1',
  `rating` INT NULL DEFAULT '0',
  `sort_order` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT '0',
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 137
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_attribute` (
  `product_id` INT NOT NULL,
  `attribute_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `text` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `attribute_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_description` (
  `product_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `tag` TEXT NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `language_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_discount` (
  `product_discount_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `customer_group_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT '0',
  `priority` INT NULL DEFAULT '1',
  `price` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `type` CHAR(1) NULL DEFAULT 'P',
  `special` TINYINT(1) NULL DEFAULT '0',
  `date_start` DATE NULL DEFAULT NULL,
  `date_end` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`product_discount_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 442
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_filter` (
  `product_id` INT NOT NULL,
  `filter_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `filter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_image` (
  `product_image_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT '0',
  PRIMARY KEY (`product_image_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2361
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_option` (
  `product_option_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `option_id` INT NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `required` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`product_option_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 227
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_option_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_option_value` (
  `product_option_value_id` INT NOT NULL AUTO_INCREMENT,
  `product_option_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `option_id` INT NULL DEFAULT NULL,
  `option_value_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `subtract` TINYINT(1) NULL DEFAULT NULL,
  `price` DECIMAL(15,4) NULL DEFAULT NULL,
  `price_prefix` VARCHAR(1) NULL DEFAULT NULL,
  `points` INT NULL DEFAULT NULL,
  `points_prefix` VARCHAR(1) NULL DEFAULT NULL,
  `weight` DECIMAL(15,8) NULL DEFAULT NULL,
  `weight_prefix` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`product_option_value_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_related`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_related` (
  `product_id` INT NOT NULL,
  `related_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `related_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_report` (
  `product_report_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT '0',
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`product_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_reward` (
  `product_reward_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT '0',
  `customer_group_id` INT NULL DEFAULT '0',
  `points` INT NULL DEFAULT '0',
  PRIMARY KEY (`product_reward_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 551
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_subscription` (
  `product_id` INT NOT NULL,
  `subscription_plan_id` INT NOT NULL,
  `customer_group_id` INT NOT NULL,
  `trial_price` DECIMAL(10,4) NULL DEFAULT NULL,
  `price` DECIMAL(10,4) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `subscription_plan_id`, `customer_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_to_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_to_category` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_to_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_to_download` (
  `product_id` INT NOT NULL,
  `download_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `download_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_to_layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_to_layout` (
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `layout_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_to_store` (
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`product_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_product_viewed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_product_viewed` (
  `product_id` INT NOT NULL,
  `viewed` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_return`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_return` (
  `return_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `firstname` VARCHAR(32) NULL DEFAULT NULL,
  `lastname` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `telephone` VARCHAR(32) NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `product` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(64) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `opened` TINYINT(1) NULL DEFAULT NULL,
  `return_reason_id` INT NULL DEFAULT NULL,
  `return_action_id` INT NULL DEFAULT NULL,
  `return_status_id` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_ordered` DATE NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`return_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_return_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_return_action` (
  `return_action_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL DEFAULT '0',
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`return_action_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_return_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_return_history` (
  `return_history_id` INT NOT NULL AUTO_INCREMENT,
  `return_id` INT NULL DEFAULT NULL,
  `return_status_id` INT NULL DEFAULT NULL,
  `notify` TINYINT(1) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`return_history_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_return_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_return_reason` (
  `return_reason_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL DEFAULT '0',
  `name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`return_reason_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_return_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_return_status` (
  `return_status_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL DEFAULT '0',
  `name` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`return_status_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `author` VARCHAR(64) NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT '0',
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_seo_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_seo_url` (
  `seo_url_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `key` VARCHAR(64) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `keyword` VARCHAR(768) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`seo_url_id`),
  INDEX `store` (`store_id` ASC) VISIBLE,
  INDEX `language` (`language_id` ASC) VISIBLE,
  INDEX `keyword` (`keyword` ASC) VISIBLE,
  INDEX `query` (`key` ASC, `value` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 973
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_session` (
  `session_id` VARCHAR(32) NOT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `expire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `expire` (`expire` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_setting` (
  `setting_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT '0',
  `code` VARCHAR(128) NULL DEFAULT NULL,
  `key` VARCHAR(128) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `serialized` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`setting_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1351
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_startup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_startup` (
  `startup_id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `action` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`startup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_statistics` (
  `statistics_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `value` DECIMAL(15,4) NULL DEFAULT NULL,
  PRIMARY KEY (`statistics_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_stock_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_stock_status` (
  `stock_status_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`stock_status_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription` (
  `subscription_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `store_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `payment_address_id` INT NULL DEFAULT NULL,
  `payment_method` TEXT NULL DEFAULT NULL,
  `shipping_address_id` INT NULL DEFAULT NULL,
  `shipping_method` TEXT NULL DEFAULT NULL,
  `subscription_plan_id` INT NULL DEFAULT NULL,
  `trial_price` DECIMAL(10,4) NULL DEFAULT NULL,
  `trial_tax` DECIMAL(10,4) NULL DEFAULT NULL,
  `trial_frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `trial_cycle` SMALLINT NULL DEFAULT NULL,
  `trial_duration` SMALLINT NULL DEFAULT NULL,
  `trial_remaining` SMALLINT NULL DEFAULT NULL,
  `trial_status` TINYINT(1) NULL DEFAULT NULL,
  `price` DECIMAL(10,4) NULL DEFAULT NULL,
  `tax` DECIMAL(10,4) NULL DEFAULT NULL,
  `frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `cycle` SMALLINT NULL DEFAULT NULL,
  `duration` SMALLINT NULL DEFAULT NULL,
  `remaining` SMALLINT NULL DEFAULT NULL,
  `date_next` DATETIME NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `subscription_status_id` INT NULL DEFAULT NULL,
  `language` VARCHAR(5) NULL DEFAULT NULL,
  `currency` VARCHAR(3) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_history` (
  `subscription_history_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NULL DEFAULT NULL,
  `subscription_status_id` INT NULL DEFAULT NULL,
  `notify` TINYINT(1) NULL DEFAULT '0',
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_history_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_log` (
  `subscription_log_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NULL DEFAULT NULL,
  `code` VARCHAR(128) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_log_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_option` (
  `subscription_option_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NULL DEFAULT NULL,
  `subscription_product_id` INT NULL DEFAULT NULL,
  `product_option_id` INT NULL DEFAULT NULL,
  `product_option_value_id` INT NULL DEFAULT '0',
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_plan` (
  `subscription_plan_id` INT NOT NULL AUTO_INCREMENT,
  `trial_frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `trial_duration` INT NULL DEFAULT NULL,
  `trial_cycle` INT NULL DEFAULT NULL,
  `trial_status` TINYINT NULL DEFAULT NULL,
  `frequency` ENUM('day', 'week', 'semi_month', 'month', 'year') NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `cycle` INT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_plan_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_plan_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_plan_description` (
  `subscription_plan_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_plan_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_product` (
  `subscription_product_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `order_product_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `trial_price` DECIMAL(10,4) NULL DEFAULT NULL,
  `trial_tax` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `price` DECIMAL(10,4) NULL DEFAULT NULL,
  `tax` DECIMAL(15,4) NULL DEFAULT '0.0000',
  PRIMARY KEY (`subscription_product_id`),
  INDEX `subscription_id` (`subscription_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_subscription_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_subscription_status` (
  `subscription_status_id` INT NOT NULL AUTO_INCREMENT,
  `language_id` INT NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`subscription_status_id`, `language_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_tax_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_tax_class` (
  `tax_class_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(32) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tax_class_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_tax_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_tax_rate` (
  `tax_rate_id` INT NOT NULL AUTO_INCREMENT,
  `geo_zone_id` INT NULL DEFAULT '0',
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `rate` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `type` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`tax_rate_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_tax_rate_to_customer_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_tax_rate_to_customer_group` (
  `tax_rate_id` INT NOT NULL,
  `customer_group_id` INT NOT NULL,
  PRIMARY KEY (`tax_rate_id`, `customer_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_tax_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_tax_rule` (
  `tax_rule_id` INT NOT NULL AUTO_INCREMENT,
  `tax_class_id` INT NULL DEFAULT NULL,
  `tax_rate_id` INT NULL DEFAULT NULL,
  `based` VARCHAR(10) NULL DEFAULT NULL,
  `priority` INT NULL DEFAULT '1',
  PRIMARY KEY (`tax_rule_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 129
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_theme` (
  `theme_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT NULL,
  `route` VARCHAR(64) NULL DEFAULT NULL,
  `code` MEDIUMTEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`theme_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_topic` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `sort_order` INT NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_topic_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_topic_description` (
  `topic_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`, `language_id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_topic_to_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_topic_to_store` (
  `topic_id` INT NOT NULL,
  `store_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`topic_id`, `store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_translation` (
  `translation_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `route` VARCHAR(64) NULL DEFAULT NULL,
  `key` VARCHAR(64) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`translation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_upload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_upload` (
  `upload_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `filename` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`upload_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_group_id` INT NULL DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(32) NULL DEFAULT NULL,
  `lastname` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(96) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT '',
  `code` VARCHAR(40) NULL DEFAULT '',
  `ip` VARCHAR(40) NULL DEFAULT '',
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_user_authorize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_user_authorize` (
  `user_authorize_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `token` VARCHAR(96) NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_authorize_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_user_group` (
  `user_group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `permission` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`user_group_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_user_login` (
  `user_login_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `ip` VARCHAR(40) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_login_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_weight_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_weight_class` (
  `weight_class_id` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(15,8) NULL DEFAULT '0.00000000',
  PRIMARY KEY (`weight_class_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_weight_class_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_weight_class_description` (
  `weight_class_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `title` VARCHAR(32) NULL DEFAULT NULL,
  `unit` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`weight_class_id`, `language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_zone` (
  `zone_id` INT NOT NULL AUTO_INCREMENT,
  `country_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `code` VARCHAR(32) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`zone_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4446
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `sampleschema`.`oc_zone_to_geo_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleschema`.`oc_zone_to_geo_zone` (
  `zone_to_geo_zone_id` INT NOT NULL AUTO_INCREMENT,
  `geo_zone_id` INT NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  `zone_id` INT NULL DEFAULT '0',
  PRIMARY KEY (`zone_to_geo_zone_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 109
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
